SET IDENTITY_INSERT [dbo].[TB_SubDistrito] ON

INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (1, 'Zona 01', 'RO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (2, 'Zona 02', 'RO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (3, 'Zona 03', 'RO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (4, 'Zona 04', 'RO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (5, 'Primeira R.A.', 'AM')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (6, 'Segunda R.A.', 'AM')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (7, 'Terceira R.A.', 'AM')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (8, 'Quarta R.A.', 'AM')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (9, 'Quinta R.A.', 'AM')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (10, 'Sexta R.A.', 'AM')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (11, 'Setima R.A.', 'AM')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (12, 'Oitava R.A.', 'AM')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (13, 'Nona R.A.', 'AM')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (14, 'Centro', 'PI')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (15, 'Leste', 'PI')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (16, 'Norte', 'PI')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (17, 'Sudeste', 'PI')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (18, 'Sul', 'PI')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (19, 'Antonio Bezerra', 'CE')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (20, 'Barra do Ceara', 'CE')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (21, 'Centro', 'CE')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (22, 'Mucuripe', 'CE')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (23, 'Antonio Bezerra', 'CE')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (24, 'Conjunto Ceara', 'CE')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (25, 'Cidade dos Funcionarios', 'CE')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (26, 'Messejana', 'CE')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (27, 'Conjunto Ceara', 'CE')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (28, 'Prefeito Jose Walter Mondubim', 'CE')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (29, 'Parangaba', 'CE')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (30, 'R.A. Norte', 'RN')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (31, 'R.A. Sul', 'RN')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (32, 'R.A. Leste', 'RN')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (33, 'R.A. Oeste', 'RN')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (34, 'RPA 01', 'PE')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (35, 'RPA 02', 'PE')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (36, 'RPA 03', 'PE')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (37, 'RPA 04', 'PE')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (38, 'RPA 05', 'PE')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (39, 'RPA 06', 'PE')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (40, 'Mangabeira', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (41, 'Pampalona', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (42, 'Santana', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (43, 'Santo Antonio', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (44, 'Subae', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (45, 'Amaralina', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (46, 'Brotas', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (47, 'Conceicao da Praia', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (48, 'Itapoa', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (49, 'Mare', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (50, 'Mares', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (51, 'Nazare', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (52, 'Paripe', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (53, 'Passo', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (54, 'Penha', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (55, 'Periperi', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (56, 'Pilar', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (57, 'Piraja', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (58, 'Plataforma', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (59, 'Santana', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (60, 'Santo Antonio', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (61, 'Sao Caetano', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (62, 'Sao Cristovao', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (63, 'Sao Pedro', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (64, 'Se', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (65, 'Valeria', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (66, 'Vitoria', 'BA')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (67, 'I REGIAO ADMINISTRATIVA', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (68, 'II REGIAO ADMINISTRATIVA', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (69, 'III REGIAO ADMINISTRATIVA', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (70, 'IV REGIAO ADMINISTRATIVA', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (71, 'V REGIAO ADMINISTRATIVA', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (72, 'VI REGIAO ADMINISTRATIVA', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (73, 'VII REGIAO ADMINISTRATIVA', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (74, 'VIII REGIAO ADMINISTRATIVA', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (75, 'IX REGIAO ADMINISTRATIVA', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (76, 'X REGIAO ADMINISTRATIVA', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (77, 'XI REGIAO ADMINISTRATIVA', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (78, 'XII REGIAO ADMINISTRATIVA', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (79, 'XIII REGIAO ADMINISTRATIVA', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (80, 'XIV REGIAO ADMINISTRATIVA', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (81, 'XV REGIAO ADMINISTRATIVA', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (82, 'XVI REGIAO ADMINISTRATIVA', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (83, 'XVII REGIAO ADMINISTRATIVA', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (84, 'Centro-Sul', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (85, 'Leste', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (86, 'Nordeste', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (87, 'Noroeste', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (88, 'Oeste', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (89, 'Pampulha', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (90, 'Venda Nova', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (91, 'Barreiro', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (92, 'Nordeste', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (93, 'Norte', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (94, 'Pampulha', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (95, 'Venda Nova', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (96, 'AR. CENTRO', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (97, 'AR. NORTE', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (98, 'AR. JARDIM DAS ALTEROSAS', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (99, 'AR. SANTA CRUZ', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (100, 'AR. IMBIRUCU', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (101, 'AR. JARDIM TEREZOPOLIS', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (102, 'AR. CITROLANDIA', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (103, 'AR. VIANOPOLIS', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (104, 'Barra', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (105, '1 Subdistrito', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (106, '2 SUBDISTRITO', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (107, 'Primeiro Subdistrito', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (108, 'Segundo Subdistrito', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (109, '1 Sub-Distrito', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (110, '2 Sub-Distrito', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (111, 'Unidade Territorial I', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (112, 'Unidade Territorial II', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (113, 'Unidade Territorial III', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (114, 'Unidade Territorial IV', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (115, 'Unidade Territorial V', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (116, 'Unidade Territorial VI', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (117, 'Unidade Territorial VII', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (118, 'Unidade Territorial VIII', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (119, 'Unidade Territorial IX', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (120, 'Unidade Territorial X', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (121, 'Unidade Territorial XI', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (122, 'Unidade Territorial XII', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (123, 'Unidade Territorial XIII', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (124, 'Unidade Territorial XIV', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (125, 'Unidade Territorial XV', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (126, 'Unidade Territorial XVI', 'MG')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (127, 'Primeiro Subdistrito', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (128, 'Segundo Subdistrito', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (129, 'Terceiro Subdistrito', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (130, 'Quarto Subdistrito', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (131, 'Barra de Macae', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (132, 'Aeroporto', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (133, 'Cabiúnas', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (134, 'Imboassica', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (135, 'URG I', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (136, 'URG II', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (137, 'URG III', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (138, 'URG IV', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (139, 'URG V', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (140, 'URG VI', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (141, 'URG VII', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (142, 'URG VIII', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (143, 'URG IX', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (144, 'URG X', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (145, 'URG XI', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (146, 'URG XII', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (147, 'Portuaria', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (148, 'Centro', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (149, 'Rio Comprido', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (150, 'Botafogo', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (151, 'Copacabana', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (152, 'Lagoa', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (153, 'Sao Cristovao', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (154, 'Tijuca', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (155, 'Vila Isabel', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (156, 'Ramos', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (157, 'Penha', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (158, 'Meier', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (159, 'Iraja', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (160, 'Madureira', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (161, 'Jacarepagua', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (162, 'Bangu', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (163, 'Campo Grande', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (164, 'Santa Cruz', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (165, 'Ilha do Governador', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (166, 'Ilha de Paqueta', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (167, 'Anchieta', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (168, 'Santa Teresa', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (169, 'Barra da Tijuca', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (170, 'Pavuna', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (171, 'Guaratiba', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (172, 'Inhaúma', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (173, 'Rocinha', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (174, 'Jacarezinho', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (175, 'Complexo do Alemao', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (176, 'Mare', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (177, 'Realengo', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (178, 'Cidade de Deus', 'RJ')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (179, 'Administracao Regional da Matriz (R.1.MZ)', 'PR')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (180, 'Administracao Regional do Boqueirao (R.2.BQ)', 'PR')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (181, 'Administracao Regional do Cajuru (R.3.CJ)', 'PR')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (182, 'Administracao Regional da Boa Vista (R.4.BV)', 'PR')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (183, 'Administracao Regional de Santa Felicidade (R.5.SF)', 'PR')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (184, 'Administracao Regional do Portao (R.7.PR)', 'PR')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (185, 'Administracao Regional Pinheirinho (R.8.PN)', 'PR')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (186, 'Administracao Regional do Bairro Novo (R.10.BN)', 'PR')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (187, 'Capitao Noronha', 'RS')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (188, 'Cerro Partido', 'RS')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (189, 'Coronel Prestes', 'RS')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (190, 'Maria Santa', 'RS')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (191, 'Pompeu Machado', 'RS')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (192, 'Santa Barbara', 'RS')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (193, 'Regiao Urbana do Centro', 'MS')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (194, 'Regiao Urbana do Prosa', 'MS')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (195, 'Regiao Urbana do Segredo', 'MS')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (196, 'Regiao Urbana do Imbirussú', 'MS')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (197, 'Regiao Urbana do Anhanduizinho', 'MS')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (198, 'Regiao Urbana do Bandeira', 'MS')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (199, 'Regiao Urbana do Lagoa', 'MS')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (200, 'Administracao Regional Norte', 'MT')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (201, 'Administracao Regional Centro-Oeste', 'MT')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (202, 'Administracao Regional Centro-Leste', 'MT')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (203, 'Administracao Regional Norte', 'MT')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (204, 'Administracao Regional Centro-Leste', 'MT')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (205, 'Administracao Regional Sul-Leste', 'MT')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (206, 'U.T.P. Central', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (207, 'U.T.P. Sul', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (208, 'U.T.P. Marista Bueno', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (209, 'U.T.P. Oeste', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (210, 'U.T.P. Aeroporto', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (211, 'U.T.P. Coimbra', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (212, 'U.T.P. Campinas', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (213, 'U.T.P. Marechal Rondon', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (214, 'U.T.P. Norte Ferroviario', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (215, 'U.T.P. Pedro Ludovico', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (216, 'U.T.P. Bueno-Nova Suica', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (217, 'U.T.P. Parque Amazonia', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (218, 'U.T.P. Jardim America', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (219, 'U.T.P. Aeroviarios', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (220, 'U.T.P. Cidade Jardim', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (221, 'U.T.P. Sudoeste', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (222, 'U.T.P. Jardim Europa', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (223, 'U.T.P. Novo Horizonte', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (224, 'U.T.P. Faicalville', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (225, 'U.T.P. Jardim Atlantico', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (226, 'U.T.P. Celina Park', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (227, 'U.T.P. Recreio dos Funcionarios Públicos', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (228, 'U.T.P. Parque Santa Rita', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (229, 'U.T.P. Parque Oeste Industrial', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (230, 'U.T.P. Joao Braz', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (231, 'U.T.P. Vila Rizzo', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (232, 'U.T.P. Jardim Petropolis', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (233, 'U.T.P. Vera Cruz', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (234, 'U.T.P. Chacaras Sao Joaquim', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (235, 'U.T.P. Vila Regina', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (236, 'U.T.P. Candida de Morais', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (237, 'U.T.P. Capuava', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (238, 'U.T.P. Maria Dilce', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (239, 'U.T.P. Urias Magalhaes', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (240, 'U.T.P. Mutirao', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (241, 'U.T.P. Finsocial', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (242, 'U.T.P. Jardim Balneario Meia Ponte', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (243, 'U.T.P. Mansoes Goianas', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (244, 'U.T.P. Campus Universitario', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (245, 'U.T.P. Itatiaia', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (246, 'U.T.P. Goiania II', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (247, 'U.T.P. Jardim Guanabara', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (248, 'U.T.P. Santa Genoveva', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (249, 'U.T.P. Aeroporto Internacional', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (250, 'U.T.P. Jao', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (251, 'U.T.P. Ceasa', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (252, 'U.T.P. Santo Hilario', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (253, 'U.T.P. Vila Pedroso', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (254, 'U.T.P. Crimeia Leste', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (255, 'U.T.P. Negrao de Lima', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (256, 'U.T.P. Vila Nova', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (257, 'U.T.P. Bairro Feliz', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (258, 'U.T.P. Leste Universitario', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (259, 'U.T.P. Jardim Goias', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (260, 'U.T.P. Jardim Novo Mundo', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (261, 'U.T.P. Agua Branca', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (262, 'U.T.P. Riviera', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (263, 'U.T.P. Autodromo', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (264, 'U.T.P. Alto da Gloria', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (265, 'U.T.P. Santo Antonio', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (266, 'U.T.P. Parque das Laranjeiras', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (267, 'U.T.P. Abadia de Goias', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (268, 'U.T.P. Parque Bom Jesus', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (269, 'U.T.P. Baliza-Itaipu', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (270, 'U.T.P. Sao Domingos', 'GO')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (271, 'Brasilia', 'DF')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (272, 'Gama', 'DF')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (273, 'Taguatinga', 'DF')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (274, 'Brazlandia', 'DF')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (275, 'Sobradinho', 'DF')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (276, 'Planaltina', 'DF')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (277, 'Paranoa', 'DF')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (278, 'Riacho Fundo', 'DF')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (279, 'Núcleo Bandeirante', 'DF')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (280, 'Ceilandia', 'DF')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (281, 'Guara', 'DF')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (282, 'Cruzeiro', 'DF')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (283, 'Samambaia', 'DF')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (284, 'Candangolandia', 'DF')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (285, 'Recanto das Emas', 'DF')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (286, 'Lago Norte', 'DF')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (287, 'Lago Sul', 'DF')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (288, 'Santa Maria', 'DF')
INSERT INTO [dbo].[TB_SubDistrito] ([ID], [DESCR], [SiglaUF]) VALUES (289, 'Sao Sebastiao', 'DF')

SET IDENTITY_INSERT [dbo].[TB_SubDistrito] OFF

