SET IDENTITY_INSERT [dbo].[TB_Microregiao] ON

INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (1, 'Porto Velho', 'RO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (2, 'Guajara-Mirim', 'RO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (3, 'Ariquemes', 'RO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (4, 'Ji-Parana', 'RO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (5, 'Alvorada D''Oeste', 'RO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (6, 'Cacoal', 'RO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (7, 'Vilhena', 'RO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (8, 'Colorado do Oeste', 'RO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (9, 'Cruzeiro do Sul', 'AC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (10, 'Tarauaca', 'AC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (11, 'Sena Madureira', 'AC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (12, 'Rio Branco', 'AC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (13, 'Brasileia', 'AC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (14, 'Rio Negro', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (15, 'Japura', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (16, 'Alto Solimoes', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (17, 'Jurua', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (18, 'Tefe', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (19, 'Coari', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (20, 'Manaus', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (21, 'Rio Preto da Eva', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (22, 'Itacoatiara', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (23, 'Parintins', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (24, 'Boca do Acre', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (25, 'Purus', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (26, 'Madeira', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (27, 'Boa Vista', 'RR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (28, 'Nordeste de Roraima', 'RR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (29, 'Caracarai', 'RR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (30, 'Sudeste de Roraima', 'RR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (31, 'Obidos', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (32, 'Santarem', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (33, 'Almeirim', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (34, 'Portel', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (35, 'Furos de Breves', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (36, 'Arari', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (37, 'Belem', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (38, 'Castanhal', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (39, 'Salgado', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (40, 'Bragantina', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (41, 'Cameta', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (42, 'Tome-Acu', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (43, 'Guama', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (44, 'Itaituba', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (45, 'Altamira', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (46, 'Tucurui', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (47, 'Paragominas', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (48, 'Sao Felix do Xingu', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (49, 'Parauapebas', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (50, 'Maraba', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (51, 'Redencao', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (52, 'Conceicao do Araguaia', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (53, 'Oiapoque', 'AP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (54, 'Amapa', 'AP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (55, 'Macapa', 'AP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (56, 'Mazagao', 'AP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (57, 'Bico do Papagaio', 'TO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (58, 'Araguaina', 'TO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (59, 'Miracema do Tocantins', 'TO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (60, 'Rio Formoso', 'TO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (61, 'Gurupi', 'TO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (62, 'Porto Nacional', 'TO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (63, 'Jalapao', 'TO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (64, 'Dianopolis', 'TO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (65, 'Litoral Ocidental Maranhense', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (66, 'Aglomeracao Urbana de Sao Luis', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (67, 'Rosario', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (68, 'Lencois Maranhenses', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (69, 'Baixada Maranhense', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (70, 'Itapecuru Mirim', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (71, 'Gurupi', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (72, 'Pindare', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (73, 'Imperatriz', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (74, 'Medio Mearim', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (75, 'Alto Mearim e Grajaú', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (76, 'Presidente Dutra', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (77, 'Baixo Parnaiba Maranhense', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (78, 'Chapadinha', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (79, 'Codo', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (80, 'Coelho Neto', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (81, 'Caxias', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (82, 'Chapadas do Alto Itapecuru', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (83, 'Porto Franco', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (84, 'Gerais de Balsas', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (85, 'Chapadas das Mangabeiras', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (86, 'Baixo Parnaiba Piauiense', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (87, 'Litoral Piauiense', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (88, 'Teresina', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (89, 'Campo Maior', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (90, 'Medio Parnaiba Piauiense', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (91, 'Valenca do Piaui', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (92, 'Alto Parnaiba Piauiense', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (93, 'Bertolinia', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (94, 'Floriano', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (95, 'Alto Medio Gurgueia', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (96, 'Sao Raimundo Nonato', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (97, 'Chapadas do Extremo Sul Piauiense', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (98, 'Picos', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (99, 'Pio IX', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (100, 'Alto Medio Caninde', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (101, 'Litoral de Camocim e Acaraú', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (102, 'Ibiapaba', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (103, 'Coreaú', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (104, 'Meruoca', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (105, 'Sobral', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (106, 'Ipu', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (107, 'Santa Quiteria', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (108, 'Itapipoca', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (109, 'Baixo Curu', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (110, 'Uruburetama', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (111, 'Medio Curu', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (112, 'Caninde', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (113, 'Baturite', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (114, 'Chorozinho', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (115, 'Cascavel', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (116, 'Fortaleza', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (117, 'Pacajus', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (118, 'Sertao de Crateus', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (119, 'Sertao de Quixeramobim', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (120, 'Sertao de Inhamuns', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (121, 'Sertao de Senador Pompeu', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (122, 'Litoral de Aracati', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (123, 'Baixo Jaguaribe', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (124, 'Medio Jaguaribe', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (125, 'Serra do Pereiro', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (126, 'Iguatu', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (127, 'Varzea Alegre', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (128, 'Lavras da Mangabeira', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (129, 'Chapada do Araripe', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (130, 'Caririacu', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (131, 'Barro', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (132, 'Cariri', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (133, 'Brejo Santo', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (134, 'Mossoro', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (135, 'Chapada do Apodi', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (136, 'Medio Oeste', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (137, 'Vale do Acu', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (138, 'Serra de Sao Miguel', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (139, 'Pau dos Ferros', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (140, 'Umarizal', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (141, 'Macau', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (142, 'Angicos', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (143, 'Serra de Santana', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (144, 'Serido Ocidental', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (145, 'Serido Oriental', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (146, 'Baixa Verde', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (147, 'Borborema Potiguar', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (148, 'Agreste Potiguar', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (149, 'Litoral Nordeste', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (150, 'Macaiba', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (151, 'Natal', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (152, 'Litoral Sul', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (153, 'Catole do Rocha', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (154, 'Cajazeiras', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (155, 'Sousa', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (156, 'Patos', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (157, 'Pianco', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (158, 'Itaporanga', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (159, 'Serra do Teixeira', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (160, 'Serido Ocidental Paraibano', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (161, 'Serido Oriental Paraibano', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (162, 'Cariri Ocidental', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (163, 'Cariri Oriental', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (164, 'Curimataú Ocidental', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (165, 'Curimataú Oriental', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (166, 'Esperanca', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (167, 'Brejo Paraibano', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (168, 'Guarabira', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (169, 'Campina Grande', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (170, 'Itabaiana', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (171, 'Umbuzeiro', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (172, 'Litoral Norte', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (173, 'Sape', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (174, 'Joao Pessoa', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (175, 'Litoral Sul', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (176, 'Araripina', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (177, 'Salgueiro', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (178, 'Pajeú', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (179, 'Sertao do Moxoto', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (180, 'Petrolina', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (181, 'Itaparica', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (182, 'Vale do Ipanema', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (183, 'Vale do Ipojuca', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (184, 'Alto Capibaribe', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (185, 'Medio Capibaribe', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (186, 'Garanhuns', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (187, 'Brejo Pernambucano', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (188, 'Mata Setentrional Pernambucana', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (189, 'Vitoria de Santo Antao', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (190, 'Mata Meridional Pernambucana', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (191, 'Itamaraca', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (192, 'Recife', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (193, 'Suape', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (194, 'Fernando de Noronha', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (195, 'Serrana do Sertao Alagoano', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (196, 'Alagoana do Sertao do Sao Francisco', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (197, 'Santana do Ipanema', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (198, 'Batalha', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (199, 'Palmeira dos Indios', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (200, 'Arapiraca', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (201, 'Traipu', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (202, 'Serrana dos Quilombos', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (203, 'Mata Alagoana', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (204, 'Litoral Norte Alagoano', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (205, 'Maceio', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (206, 'Sao Miguel dos Campos', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (207, 'Penedo', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (208, 'Sergipana do Sertao do Sao Francisco', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (209, 'Carira', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (210, 'Nossa Senhora das Dores', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (211, 'Agreste de Itabaiana', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (212, 'Tobias Barreto', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (213, 'Agreste de Lagarto', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (214, 'Propria', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (215, 'Cotinguiba', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (216, 'Japaratuba', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (217, 'Baixo Cotinguiba', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (218, 'Aracaju', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (219, 'Boquim', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (220, 'Estancia', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (221, 'Barreiras', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (222, 'Cotegipe', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (223, 'Santa Maria da Vitoria', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (224, 'Juazeiro', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (225, 'Paulo Afonso', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (226, 'Barra', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (227, 'Bom Jesus da Lapa', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (228, 'Senhor do Bonfim', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (229, 'Irece', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (230, 'Jacobina', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (231, 'Itaberaba', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (232, 'Feira de Santana', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (233, 'Jeremoabo', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (234, 'Euclides da Cunha', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (235, 'Ribeira do Pombal', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (236, 'Serrinha', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (237, 'Alagoinhas', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (238, 'Entre Rios', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (239, 'Catu', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (240, 'Santo Antonio de Jesus', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (241, 'Salvador', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (242, 'Boquira', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (243, 'Seabra', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (244, 'Jequie', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (245, 'Livramento do Brumado', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (246, 'Guanambi', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (247, 'Brumado', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (248, 'Vitoria da Conquista', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (249, 'Itapetinga', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (250, 'Valenca', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (251, 'Ilheus-Itabuna', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (252, 'Porto Seguro', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (253, 'Unai', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (254, 'Paracatu', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (255, 'Januaria', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (256, 'Janaúba', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (257, 'Salinas', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (258, 'Pirapora', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (259, 'Montes Claros', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (260, 'Grao Mogol', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (261, 'Bocaiúva', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (262, 'Diamantina', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (263, 'Capelinha', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (264, 'Aracuai', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (265, 'Pedra Azul', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (266, 'Almenara', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (267, 'Teofilo Otoni', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (268, 'Nanuque', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (269, 'Ituiutaba', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (270, 'Uberlandia', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (271, 'Patrocinio', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (272, 'Patos de Minas', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (273, 'Frutal', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (274, 'Uberaba', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (275, 'Araxa', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (276, 'Tres Marias', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (277, 'Curvelo', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (278, 'Bom Despacho', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (279, 'Sete Lagoas', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (280, 'Conceicao do Mato Dentro', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (281, 'Para de Minas', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (282, 'Belo Horizonte', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (283, 'Itabira', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (284, 'Itaguara', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (285, 'Ouro Preto', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (286, 'Conselheiro Lafaiete', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (287, 'Guanhaes', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (288, 'Pecanha', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (289, 'Governador Valadares', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (290, 'Mantena', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (291, 'Ipatinga', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (292, 'Caratinga', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (293, 'Aimores', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (294, 'Pi¿i', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (295, 'Divinopolis', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (296, 'Formiga', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (297, 'Campo Belo', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (298, 'Oliveira', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (299, 'Passos', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (300, 'Sao Sebastiao do Paraiso', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (301, 'Alfenas', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (302, 'Varginha', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (303, 'Pocos de Caldas', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (304, 'Pouso Alegre', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (305, 'Santa Rita do Sapucai', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (306, 'Sao Lourenco', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (307, 'Andrelandia', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (308, 'Itajuba', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (309, 'Lavras', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (310, 'Sao Joao Del Rei', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (311, 'Barbacena', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (312, 'Ponte Nova', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (313, 'Manhuacu', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (314, 'Vicosa', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (315, 'Muriae', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (316, 'Uba', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (317, 'Juiz de Fora', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (318, 'Cataguases', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (319, 'Barra de Sao Francisco', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (320, 'Nova Venecia', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (321, 'Colatina', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (322, 'Montanha', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (323, 'Sao Mateus', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (324, 'Linhares', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (325, 'Afonso Claudio', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (326, 'Santa Teresa', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (327, 'Vitoria', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (328, 'Guarapari', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (329, 'Alegre', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (330, 'Cachoeiro de Itapemirim', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (331, 'Itapemirim', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (332, 'Itaperuna', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (333, 'Santo Antonio de Padua', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (334, 'Campos dos Goytacazes', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (335, 'Macae', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (336, 'Tres Rios', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (337, 'Cantagalo-Cordeiro', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (338, 'Nova Friburgo', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (339, 'Santa Maria Madalena', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (340, 'Bacia de Sao Joao', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (341, 'Lagos', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (342, 'Vale do Paraiba Fluminense', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (343, 'Barra do Pirai', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (344, 'Baia da Ilha Grande', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (345, 'Vassouras', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (346, 'Serrana', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (347, 'Macacu-Caceribu', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (348, 'Itaguai', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (349, 'Rio de Janeiro', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (350, 'Jales', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (351, 'Fernandopolis', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (352, 'Votuporanga', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (353, 'Sao Jose do Rio Preto', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (354, 'Catanduva', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (355, 'Auriflama', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (356, 'Nhandeara', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (357, 'Novo Horizonte', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (358, 'Barretos', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (359, 'Sao Joaquim da Barra', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (360, 'Ituverava', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (361, 'Franca', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (362, 'Jaboticabal', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (363, 'Ribeirao Preto', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (364, 'Batatais', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (365, 'Andradina', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (366, 'Aracatuba', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (367, 'Birigui', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (368, 'Lins', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (369, 'Bauru', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (370, 'Jaú', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (371, 'Avare', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (372, 'Botucatu', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (373, 'Araraquara', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (374, 'Sao Carlos', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (375, 'Rio Claro', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (376, 'Limeira', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (377, 'Piracicaba', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (378, 'Pirassununga', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (379, 'Sao Joao da Boa Vista', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (380, 'Moji-Mirim', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (381, 'Campinas', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (382, 'Amparo', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (383, 'Dracena', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (384, 'Adamantina', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (385, 'Presidente Prudente', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (386, 'Tupa', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (387, 'Marilia', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (388, 'Assis', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (389, 'Ourinhos', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (390, 'Itapeva', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (391, 'Itapetininga', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (392, 'Tatui', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (393, 'Capao Bonito', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (394, 'Piedade', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (395, 'Sorocaba', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (396, 'Jundiai', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (397, 'Braganca Paulista', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (398, 'Campos do Jordao', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (399, 'Sao Jose dos Campos', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (400, 'Guaratingueta', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (401, 'Bananal', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (402, 'Paraibuna/Paraitinga', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (403, 'Caraguatatuba', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (404, 'Registro', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (405, 'Itanhaem', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (406, 'Osasco', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (407, 'Franco da Rocha', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (408, 'Guarulhos', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (409, 'Itapecerica da Serra', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (410, 'Sao Paulo', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (411, 'Moji das Cruzes', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (412, 'Santos', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (413, 'Paranavai', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (414, 'Umuarama', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (415, 'Cianorte', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (416, 'Goioere', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (417, 'Campo Mourao', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (418, 'Astorga', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (419, 'Porecatú', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (420, 'Florai', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (421, 'Maringa', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (422, 'Apucarana', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (423, 'Londrina', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (424, 'Faxinal', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (425, 'Ivaipora', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (426, 'Assai', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (427, 'Cornelio Procopio', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (428, 'Jacarezinho', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (429, 'Ibaiti', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (430, 'Wesceslau Braz', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (431, 'Telemaco Borba', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (432, 'Jaguariaiva', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (433, 'Ponta Grossa', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (434, 'Toledo', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (435, 'Cascavel', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (436, 'Foz do Iguacu', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (437, 'Capanema', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (438, 'Francisco Beltrao', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (439, 'Pato Branco', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (440, 'Pitanga', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (441, 'Guarapuava', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (442, 'Palmas', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (443, 'Prudentopolis', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (444, 'Irati', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (445, 'Uniao da Vitoria', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (446, 'Sao Mateus do Sul', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (447, 'Cerro Azul', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (448, 'Lapa', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (449, 'Curitiba', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (450, 'Paranagua', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (451, 'Rio Negro', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (452, 'Sao Miguel d''Oeste', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (453, 'Chapeco', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (454, 'Xanxere', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (455, 'Joacaba', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (456, 'Concordia', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (457, 'Canoinhas', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (458, 'Sao Bento do Sul', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (459, 'Joinville', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (460, 'Curitibanos', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (461, 'Campos de Lages', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (462, 'Rio do Sul', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (463, 'Blumenau', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (464, 'Itajai', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (465, 'Ituporanga', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (466, 'Tijucas', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (467, 'Florianopolis', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (468, 'Tabuleiro', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (469, 'Tubarao', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (470, 'Criciúma', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (471, 'Ararangua', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (472, 'Santa Rosa', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (473, 'Tres Passos', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (474, 'Frederico Westphalen', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (475, 'Erechim', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (476, 'Sananduva', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (477, 'Cerro Largo', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (478, 'Santo Angelo', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (479, 'Ijui', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (480, 'Carazinho', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (481, 'Passo Fundo', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (482, 'Cruz Alta', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (483, 'Nao-Me-Toque', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (484, 'Soledade', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (485, 'Guapore', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (486, 'Vacaria', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (487, 'Caxias do Sul', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (488, 'Santiago', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (489, 'Santa Maria', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (490, 'Restinga Seca', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (491, 'Santa Cruz do Sul', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (492, 'Lajeado-Estrela', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (493, 'Cachoeira do Sul', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (494, 'Montenegro', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (495, 'Gramado-Canela', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (496, 'Sao Jeronimo', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (497, 'Porto Alegre', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (498, 'Osorio', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (499, 'Camaqua', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (500, 'Campanha Ocidental', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (501, 'Campanha Central', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (502, 'Campanha Meridional', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (503, 'Serras de Sudeste', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (504, 'Pelotas', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (505, 'Jaguarao', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (506, 'Litoral Lagunar', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (507, 'Baixo Pantanal', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (508, 'Aquidauana', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (509, 'Alto Taquari', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (510, 'Campo Grande', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (511, 'Cassilandia', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (512, 'Paranaiba', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (513, 'Tres Lagoas', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (514, 'Nova Andradina', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (515, 'Bodoquena', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (516, 'Dourados', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (517, 'Iguatemi', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (518, 'Aripuana', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (519, 'Alta Floresta', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (520, 'Colider', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (521, 'Parecis', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (522, 'Arinos', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (523, 'Alto Teles Pires', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (524, 'Sinop', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (525, 'Paranatinga', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (526, 'Norte Araguaia', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (527, 'Canarana', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (528, 'Medio Araguaia', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (529, 'Alto Guapore', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (530, 'Tangara da Serra', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (531, 'Jauru', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (532, 'Alto Paraguai', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (533, 'Rosario Oeste', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (534, 'Cuiaba', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (535, 'Alto Pantanal', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (536, 'Primavera do Leste', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (537, 'Tesouro', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (538, 'Rondonopolis', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (539, 'Alto Araguaia', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (540, 'Sao Miguel do Araguaia', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (541, 'Rio Vermelho', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (542, 'Aragarcas', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (543, 'Porangatu', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (544, 'Chapada dos Veadeiros', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (545, 'Ceres', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (546, 'Anapolis', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (547, 'Ipora', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (548, 'Anicuns', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (549, 'Goiania', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (550, 'Vao do Parana', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (551, 'Entorno de Brasilia', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (552, 'Sudoeste de Goias', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (553, 'Vale do Rio dos Bois', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (554, 'Meia Ponte', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (555, 'Pires do Rio', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (556, 'Catalao', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (557, 'Quirinopolis', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (558, 'Brasilia', 'DF')

SET IDENTITY_INSERT [dbo].[TB_Microregiao] OFF

