SET IDENTITY_INSERT [dbo].[TB_Pais] ON

INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (1, 'AFG', 'PS', 'Afeganistao')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (2, 'AFS', 'EN', 'Africa do Sul')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (3, 'AHL', 'NL', 'Antilhas Holandesas')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (4, 'ALB', 'SQ', 'Albania')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (5, 'ANB', 'EN', 'Antigua')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (6, 'AND', 'CA', 'Andorra')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (7, 'ANG', 'PT', 'Angola')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (8, 'ARA', 'AR', 'Arabia Saudita')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (9, 'ARG', 'ES', 'Argentina')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (10, 'ARL', 'ES', 'Argelia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (11, 'ARM', 'RU', 'Armenia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (12, 'ASM', 'EN', 'Samoa Americana')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (13, 'ATC', 'EN', 'Antartida')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (14, 'AUS', 'EN', 'Australia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (15, 'AUT', 'DE', 'Austria')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (16, 'AZE', 'RU', 'Azerbaijao')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (17, 'BAR', 'AR', 'Barein')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (18, 'BEA', 'RU', 'Belarus')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (19, 'BEL', 'FR', 'Belgica')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (20, 'BEN', 'EN', 'Benin')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (21, 'BER', 'EN', 'Bermudas')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (22, 'BGD', 'BN', 'Bangladesh')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (23, 'BHS', 'EN', 'Bahamas')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (24, 'BIR', 'BM', 'Birmania')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (25, 'BKF', 'FR', 'Burkina Fasso')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (26, 'BLZ', 'EN', 'Belize')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (27, 'BOL', 'ES', 'Bolivia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (28, 'BOS', 'EN', 'Bosnia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (29, 'BOT', 'EN', 'Botsuana')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (30, 'BRA', 'PT', 'Brasil')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (31, 'BRB', 'EN', 'Barbados')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (32, 'BRN', 'MS', 'Brunei')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (33, 'BUL', 'BG', 'Bulgaria')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (34, 'BUR', 'FR', 'Burundi')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (35, 'BUT', 'DZ', 'Butao')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (36, 'CAM', 'EN', 'Camaroes')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (37, 'CAN', 'EN', 'Canada')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (38, 'CAT', 'AR', 'Catar')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (39, 'CAZ', 'RU', 'Cazaquistao')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (40, 'CBJ', 'KM', 'Camboja')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (41, 'CBV', 'PT', 'Cabo Verde')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (42, 'CCK', 'EN', 'Ilhas Cocos')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (43, 'CHA', 'FR', 'Chade')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (44, 'CHL', 'ES', 'Chile')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (45, 'CHN', 'ZH', 'China')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (46, 'CHP', 'EL', 'Chipre')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (47, 'CIN', 'EN', 'Cingapura')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (48, 'CMF', 'FR', 'Costa do Marfim')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (49, 'COK', 'EN', 'Ilhas Cook')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (50, 'COL', 'EN', 'Colombia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (51, 'COM', 'EN', 'Comores')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (52, 'CON', 'FR', 'Congo')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (53, 'CRC', 'ES', 'Costa Rica')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (54, 'CRN', 'KO', 'Coreia do Norte')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (55, 'CRO', 'EN', 'Croacia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (56, 'CRS', 'KO', 'Coreia do Sul')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (57, 'CUB', 'ES', 'Cuba')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (58, 'CXR', 'EN', 'Christmas Island')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (59, 'CYM', 'EN', 'Ilhas Cayman')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (60, 'DIN', 'DA', 'Dinamarca')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (61, 'DJI', 'EN', 'Djibuti')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (62, 'DOM', 'ES', 'Republica Dominicana')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (63, 'DON', 'EN', 'Dominica')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (64, 'EAU', 'AR', 'Emirados Arabes')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (65, 'EGI', 'AR', 'Egito')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (66, 'ELS', 'ES', 'El Salvador')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (67, 'EQU', 'ES', 'Equador')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (68, 'ERT', 'AR', 'Eritrea')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (69, 'ESC', 'EN', 'Escocia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (70, 'ESH', 'EN', 'Western Sahara')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (71, 'ESP', 'ES', 'Espanha')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (72, 'EST', 'RU', 'Estonia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (73, 'ETP', 'AM', 'Etiopia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (74, 'EUA', 'EN', 'Estados Unidos')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (75, 'FIL', 'FL', 'Filipinas')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (76, 'FIN', 'EN', 'Finlandia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (77, 'FJI', 'EN', 'Fiji')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (78, 'FLK', 'EN', 'Ilhas Falkland')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (79, 'FOR', 'ZH', 'Formosa')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (80, 'FRA', 'FR', 'Franca')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (81, 'FSM', 'EN', 'Micronesia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (82, 'GAB', 'FR', 'Gabao')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (83, 'GAL', 'EN', 'Gales')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (84, 'GAM', 'EN', 'Gambia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (85, 'GAN', 'EN', 'Gana')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (86, 'GBR', 'EN', 'Gra-Bretanha')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (87, 'GDL', 'FR', 'Guadalupe')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (88, 'GEO', 'RU', 'Georgia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (89, 'GFR', 'FR', 'Guiana Francesa')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (90, 'GIB', 'EN', 'Gibraltar')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (91, 'GNB', 'PT', 'Guine Bissau')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (92, 'GNE', 'ES', 'Guine')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (93, 'GNQ', 'EN', 'Guine Equatorial')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (94, 'GRD', 'EN', 'Granada')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (95, 'GRE', 'EL', 'Grecia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (96, 'GRL', 'EN', 'Groenlandia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (97, 'GUA', 'ES', 'Guatemala')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (98, 'GUI', 'EN', 'Guiana')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (99, 'GUM', 'EN', 'Guam')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (100, 'HKG', 'EN', 'Hong Kong')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (101, 'HOL', 'NL', 'Holanda')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (102, 'HON', 'ES', 'Honduras')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (103, 'HTI', 'FR', 'Haiti')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (104, 'HUN', 'HU', 'Hungria')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (105, 'IDN', 'IN', 'Indonesia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (106, 'IEM', 'AR', 'Iemem')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (107, 'IFA', 'DA', 'Ilhas Faroe')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (108, 'IMH', 'EN', 'Ilhas Marshall')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (109, 'IMS', 'AR', 'Iemen do Sul')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (110, 'IND', 'HI', 'India')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (111, 'ING', 'EN', 'Inglaterra')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (112, 'IOT', 'EN', 'Britsh Indian Ocean')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (113, 'IRA', 'FA', 'Ira')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (114, 'IRL', 'EN', 'Irlanda')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (115, 'IRN', 'EN', 'Irlanda do Norte')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (116, 'IRQ', 'AR', 'Iraque')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (117, 'ISL', 'IS', 'Islandia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (118, 'ISR', 'IW', 'Israel')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (119, 'ITA', 'IT', 'Italia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (120, 'IUG', 'SH', 'Iugoslavia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (121, 'IVA', 'EN', 'Ilhas Virgens EUA')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (122, 'JAM', 'EN', 'Jamaica')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (123, 'JAP', 'JA', 'Japao')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (124, 'JOR', 'AR', 'Jordania')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (125, 'KIR', 'EN', 'Kiribati')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (126, 'KNA', 'EN', 'Sao Cristovao Nevis')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (127, 'KWT', 'AR', 'Kuweit')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (128, 'LAO', 'LO', 'Laos')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (129, 'LBN', 'AR', 'Libano')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (130, 'LBR', 'EN', 'Liberia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (131, 'LCA', 'EN', 'Santa Lucia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (132, 'LES', 'EN', 'Lesoto')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (133, 'LET', 'RU', 'Letonia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (134, 'LIB', 'AR', 'Libia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (135, 'LIE', 'DE', 'Liechtenstein')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (136, 'LIT', 'RU', 'Lituania')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (137, 'LUX', 'FR', 'Luxemburgo')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (138, 'MAC', 'PT', 'Macau')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (139, 'MAD', 'FR', 'Madagascar')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (140, 'MAL', 'MS', 'Malasia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (141, 'MAR', 'AR', 'Marrocos')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (142, 'MAU', 'EN', 'Mauricio')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (143, 'MBQ', 'PT', 'Mocambique')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (144, 'MCD', 'MK', 'Macedonia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (145, 'MDV', 'EN', 'Maldivas')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (146, 'MEX', 'ES', 'Mexico')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (147, 'MGL', 'MN', 'Mongolia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (148, 'MID', 'EN', 'Ilhas Midway')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (149, 'MLI', 'FR', 'Mali')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (150, 'MLT', 'MT', 'Malta')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (151, 'MLV', 'EN', 'Malavi')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (152, 'MMR', 'EN', 'Mianmar')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (153, 'MOL', 'RU', 'Moldova')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (154, 'MON', 'FR', 'Monaco')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (155, 'MRT', 'FR', 'Martinica')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (156, 'MSR', 'EN', 'Montserrat')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (157, 'MTN', 'AR', 'Mauritania')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (158, 'NAM', 'EN', 'Namibia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (159, 'NCL', 'FR', 'Nova Caledonia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (160, 'NFK', 'EN', 'Ilhas Norfolk')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (161, 'NGA', 'EN', 'Nigeria')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (162, 'NIC', 'ES', 'Nicaragua')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (163, 'NIG', 'FR', 'Niger')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (164, 'NIU', 'EN', 'Niue')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (165, 'NOR', 'NO', 'Noruega')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (166, 'NPL', 'NE', 'Nepal')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (167, 'NRU', 'EN', 'Nauru')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (168, 'NZL', 'EN', 'Nova Zelandia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (169, 'OMA', 'AR', 'Oma')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (170, 'PAN', 'ES', 'Panama')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (171, 'PAQ', 'UR', 'Paquistao')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (172, 'PCI', 'EN', 'Pacific Islands')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (173, 'PCN', 'EN', 'Pitcairn')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (174, 'PER', 'ES', 'Peru')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (175, 'PLF', 'FR', 'Polinesia Francesa')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (176, 'PLU', 'EN', 'Palau')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (177, 'PNG', 'EN', 'Papua Nova Guine')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (178, 'POL', 'PL', 'Polonia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (179, 'POR', 'PT', 'Portugal')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (180, 'PRG', 'ES', 'Paraguai')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (181, 'PTR', 'ES', 'Porto Rico')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (182, 'QUE', 'SW', 'Quenia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (183, 'QUI', 'RU', 'Quirgistao')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (184, 'RCA', 'FR', 'Rep.Centro-Africana')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (185, 'REU', 'FR', 'Reuniao')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (186, 'RFA', 'DE', 'Alemanha')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (187, 'ROM', 'RO', 'Romenia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (188, 'RSS', 'RU', 'Russia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (189, 'RUA', 'FR', 'Ruanda')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (190, 'SAM', 'EN', 'Samoa Ocidental')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (191, 'SEN', 'FR', 'Senegal')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (192, 'SHN', 'EN', 'Ilhas Santa Helena')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (193, 'SIR', 'AR', 'Siria')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (194, 'SLB', 'EN', 'Ilhas Salamao')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (195, 'SMR', 'IT', 'San Marino')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (196, 'SOM', 'AR', 'Somalia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (197, 'SPM', 'EN', 'Sao Pedro Miquelon')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (198, 'SRI', 'SI', 'Sri Lanka')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (199, 'SRL', 'EN', 'Serra Leoa')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (200, 'STP', 'EN', 'Sao Tome e Principe')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (201, 'SUA', 'EN', 'Suazilandia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (202, 'SUD', 'AR', 'Sudao')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (203, 'SUE', 'SV', 'Suecia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (204, 'SUI', 'FR', 'Suica')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (205, 'SUR', 'NL', 'Suriname')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (206, 'SVK', 'EN', 'Eslovaquia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (207, 'SVN', 'EN', 'Eslovenia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (208, 'SYC', 'EN', 'Seychelles')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (209, 'TAD', 'RU', 'Tadjaquistao')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (210, 'TAI', 'TH', 'Tailandia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (211, 'TAN', 'EN', 'Tanzania')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (212, 'TCA', 'EN', 'Ilhas Turcas Caicos')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (213, 'TCH', 'CS', 'Republica Tcheca')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (214, 'TGO', 'FR', 'Togo')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (215, 'TKL', 'EN', 'Tokelau')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (216, 'TMP', 'EN', 'Timor')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (217, 'TON', 'EN', 'Tonga')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (218, 'TRT', 'EN', 'Trinidad e Tobago')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (219, 'TUC', 'RU', 'Turcomenistao')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (220, 'TUN', 'AR', 'Tunisia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (221, 'TUR', 'TR', 'Turquia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (222, 'TUV', 'EN', 'Tuvalu')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (223, 'UCR', 'RU', 'Ucrania')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (224, 'UGA', 'EN', 'Uganda')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (225, 'URS', 'RU', 'Uniao Sovietica')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (226, 'URU', 'ES', 'Uruguai')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (227, 'UZB', 'RU', 'Uzbekistan')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (228, 'VAT', 'IT', 'Vaticano')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (229, 'VCT', 'EN', 'Sao Vicente Granadi')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (230, 'VEN', 'ES', 'Venezuela')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (231, 'VGB', 'EN', 'Ilhas Virgens GBR')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (232, 'VTN', 'VI', 'Vietna')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (233, 'VUT', 'EN', 'Vanuatu')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (234, 'WAK', 'EN', 'Ilhas Wake')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (235, 'WLF', 'EN', 'Ilhas Wallis Futuna')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (236, 'ZAN', 'EN', 'Zambia')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (237, 'ZAR', 'FR', 'Zaire')
INSERT INTO [dbo].[TB_Pais] ([ID], [SIGLA_PAIS], [COD_IDIOMA], [DESCR]) VALUES (238, 'ZIN', 'EN', 'Zimbabue')

SET IDENTITY_INSERT [dbo].[TB_Pais] OFF

